### ISSUE TITLE
ModuleNotFoundError: No module named 'proxy_machine'

### ISSUE THREAD

**Issue by Tolly2991** [batiscuff/proxy_machine#2]
Hi I really like your git! thanks for that. but when im trying to run it Ive got this issue:

> Traceback (most recent call last):
>   File "__main__.py", line 8, in <module>
>     import proxy_machine.otherproxies as otherproxies
> ModuleNotFoundError: No module named 'proxy_machine'

**Comment by batiscuff** [comment]
Hey! If you want to use `otherproxies` as a module, you must be in the `proxy_machine` directory (where the **LICENSE** is located, **README.md**), or just move the `otherproxies.py` to the directory you need and use it already there. Since this application is not a library / module, this application is to run only in command line mode.
